[book]
title = "FinanceQuery Documentation"
authors = ["Harvey Tseng"]
description = "Documentation for FinanceQuery - A financial data library built with Rust"
language = "en"
multilingual = false
src = "book"

[build]
build-dir = "book/output"
create-missing = true

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/Verdenroz/finance-query"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/Verdenroz/finance-query/edit/master/book/{path}"
site-url = "/finance-query/"
cname = ""
curly-quotes = true
mathjax-support = false
copy-fonts = true
no-section-label = false
additional-css = []
additional-js = []

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = false
copy-js = true
line-numbers = false
runnable = false

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.print]
enable = true
